### ISSUE TITLE
[BUG] V3版本下watcher配置文件配置错误，hyperf的Watcher组件不能正常工作

### ISSUE THREAD

**Issue by MYxu** [mineadmin/MineAdmin#389]
### bug描述:
watcher.php配置文件指定监听api目录，但这个目录是不存在的，而hyperf的watcher组件收集文件时，如果这个监听目录不存在时就直接报错不能正常工作了。

**Comment by zds-s** [comment]
v3 没有 api 目录了吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月30日(周三) 上午9:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [mineadmin/MineAdmin] [BUG] V3版本下watcher配置文件配置错误，hyperf的Watcher组件不能正常工作 (Issue #389)




 
bug描述:
 
watcher.php配置文件指定监听api目录，但这个目录是不存在的，而hyperf的watcher组件收集文件时，如果这个监听目录不存在时就直接报错不能正常工作了。

**Comment by MYxu** [comment]
> v3 没有 api 目录了吧
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年10月30日(周三) 上午9:48 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [mineadmin/MineAdmin] [BUG] V3版本下watcher配置文件配置错误，hyperf的Watcher组件不能正常工作 (Issue #389) bug描述: watcher.php配置文件指定监听api目录，但这个目录是不存在的，而hyperf的watcher组件收集文件时，如果这个监听目录不存在时就直接报错不能正常工作了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

![image](https://github.com/user-attachments/assets/bd557e42-0a74-44e1-a4b0-259f75363200)
但配置文件没有去掉监听这个api目录

**Comment by zds-s** [comment]
一般是用的项目下的 watch，先手动去掉吧。要有空的话提个 pr 把 api 目录去掉



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月30日(周三) 晚上6:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mineadmin/MineAdmin] [BUG] V3版本下watcher配置文件配置错误，hyperf的Watcher组件不能正常工作 (Issue #389)




  
v3 没有 api 目录了吧
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年10月30日(周三) 上午9:48 收件人: @.&gt;; 抄送: @.&gt;; 主题: [mineadmin/MineAdmin] [BUG] V3版本下watcher配置文件配置错误，hyperf的Watcher组件不能正常工作 (Issue #389) bug描述: watcher.php配置文件指定监听api目录，但这个目录是不存在的，而hyperf的watcher组件收集文件时，如果这个监听目录不存在时就直接报错不能正常工作了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
image.png (view on web)
 但配置文件没有去掉监听这个api目录
